name: React Testing and Deploying

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Give permissions for script to run
        run: |
          sudo chmod +x build-deploy.sh
      - name: Run script
        run: ./build-deploy.sh