name: React Testing and Deploying

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'GuillaumeFalourd'
        repository: 'poc-github-actions'

      - name: Access cloned repository
        run: |
          cd poc-github-actions
          ls -la